Fakebook.Posts/Fakebook.Posts.DataAccess/Fakebook.Posts.DataAccess.csproj, Fakebook.Posts/Fakebook.Posts.Domain/Fakebook.Posts.Domain.csproj, Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/CommentsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Fakebook.Posts.RestApi.csproj, Fakebook.Posts/Fakebook.Posts.RestApi/Program.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Properties/launchSettings.json, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.RestApi/appsettings.Development.json, Fakebook.Posts/Fakebook.Posts.RestApi/appsettings.json, Fakebook.Posts/Fakebook.Posts.UnitTests/Fakebook.Posts.UnitTests.csproj, Fakebook.Posts/Fakebook.Posts.UnitTests/UnitTest1.cs, Fakebook.Posts/Fakebook.Posts.sln
Set up projects:
- Fakebook.Posts.DataAccess
- Fakebook.Posts.Domain
- Fakebook.Posts.RestApi
- Fakebook.Posts.UnitTests
=> Initial skeleton project

azure-pipelines.yml
cf. https://github.com/2011-fakebook-project3/notifications/pull/10, https://github.com/2011-fakebook-project3/profile/pull/3
=> normalize ci, allow test failures outside main.

Fakebook.Posts/Fakebook.Posts.DataAccess/Fakebook.Posts.DataAccess.csproj, Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs
Code-first context class and data access models created
=> ft-code-first-db

Fakebook.Posts/Fakebook.Posts.DataAccess/Models/User.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/User.cs
=> Ft user models

Fakebook.Posts/Fakebook.Posts.DataAccess/Fakebook.Posts.DataAccess.csproj, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Fakebook.Posts.Domain.csproj, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs
=> repository skeleton

Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/FollowsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IFollowsRepository.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/DataMapper.Test/DataMapperTest.cs
Rename mapper for User -> Follow and their respective tests
Include new Follow Repository with:
- GetFollowedEmails
- GetFollowerEmails
=> Ft follow repo

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Fakebook.Posts.RestApi.csproj, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs
Fixed dbcontext date type to proper PostgreSQL date type
=> Fixed date time from dbcontext

Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs
Routes implemented
- `api/Posts/{id}/comments/{commentId}/like`
- `api/Posts/{id}/like`
=> Like Posts API - Feature Implementation

Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs
Post domain model now creates a new list of comments when constructor is called
=> Post constructor instantiates a new empty list of comments

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/PostRepository_CreateTest.cs
- Fix bug in Repository testing where a domain model was being added to the context instead of a data access model
- Fix bug where data mapper was to mapping a null collection of comments
- Configure Jwtbearer for authentication
=> Ft like api

Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/CommentsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Controllers/DeleteCommentTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Controllers/DeletePostTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/DeleteCommentTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/DeletePostTests.cs
- Implements `DeleteAsync` actions for the PostsController and CommentsController
- Implements `DeletePostAsync` and `DeleteCommentAsync` in the PostsRepository
- Unit testing for all of the above methods
=> Ft delete posts

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/CommentLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/PostLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/PostRepository_CreateTest.cs
User is able to like and unlike posts and comments. 
- Database table for likes
- Like data access model
- Repository methods to like and unlike in Post Repository
- Controller HTTP methods to like and unlike Posts and Comments in Post Controller
- Included instantiation of a new hashset of comments in the post constructor
=> User Story - Like & Unlike Posts and Comments

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/CommentLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/PostLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/PostRepository_CreateTest.cs
=> Ft edit posts update main

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/CommentLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Models/PostLike.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/PostRepository_CreateTest.cs
=> Ft post image update main

Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/FollowsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Controllers/FollowsControllerTests.cs
- Add `FollowsController`
- Add `PutAsync` and `DeleteAsync` For follow and unfollow at route `api/Follows/{email}`
=> Feature Implementation - Follow users by email

Fakebook.Posts/Fakebook.Posts.RestApi/Startup.cs, Fakebook.Posts/Fakebook.Posts.RestApi/appsettings.json
Dummy connection string in appsettings.json, enabled CORS in startup file
=> [URGENT] Ft connection string

Fakebook.Posts/Fakebook.Posts.DataAccess/Mappers/DataMapper.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Comment.cs, Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/DataMapper.Test/DataMapperTest.cs
- Add likes to domain classes
- Add likes conversion to datamapper
- Add likes to tests for datamapper
=> Feature Likes

Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs
[Authorize] added to necessary post controller methods, fixes issue of email not being retrieved  from the auth token
=> [URGENT] Auth enabled for post controller

Fakebook.Posts/Fakebook.Posts.Domain/Interfaces/IPostsRepository.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs
=> URGENT: switch to SQL query for newsfeed

Fakebook.Posts/Fakebook.Posts.DataAccess/Repositories/PostsRepository.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs
Jay is doing dinner so could you merge this for me nick?
=> attempt to fix sql with quotation marks and schema

Fakebook.Posts/Fakebook.Posts.DataAccess/FakebookPostsContext.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Migrations/20210113215145_seedData.Designer.cs, Fakebook.Posts/Fakebook.Posts.DataAccess/Migrations/20210113215145_seedData.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/DeleteCommentTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/DeletePostTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/PostRepository.Test/PostRepository_CreateTest.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Repositories/EditPostTests.cs
seed some data into the database from the context class
=> Ft seed data

Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/CommentsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/FollowsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Services/BlobService.cs
Consistent documentation across controllers, as well as for Blob Service.  Renamed Controller method endpoints by removing Async from the end of them.
=> Documentation/Name Changes

Fakebook.Posts/Fakebook.Posts.UnitTests/PostTest.cs
We added failing test in our Unit testing directory.
=> Adding failing test

Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs
We made our unit test pass by adding our business logic in the post.cs file.
=> Passing test

Fakebook.Posts/Fakebook.Posts.UnitTests/CommentTest.cs
We added failing test for our business logic in the commend model.
=> We added failing test for our business logic comment model.

Fakebook.Posts/Fakebook.Posts.Domain/Constants/Constants.cs, Fakebook.Posts/Fakebook.Posts.RestApi/DTOs/EditCommentDTO.cs, Fakebook.Posts/Fakebook.Posts.RestApi/DTOs/EditPostDTO.cs, Fakebook.Posts/Fakebook.Posts.RestApi/DTOs/FollowerDTO.cs, Fakebook.Posts/Fakebook.Posts.RestApi/DTOs/NewCommentDTO.cs, Fakebook.Posts/Fakebook.Posts.RestApi/DTOs/NewPostDTO.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Controllers/DeleteCommentTests.cs, Fakebook.Posts/Fakebook.Posts.UnitTests/Controllers/PostControllerTest.cs
Added DTOs to be used in integration testing, and got failing tests for controllers not able to handle DTO formatted requests
=> Dto validation ttdfail

Fakebook.Posts/Fakebook.Posts.Domain/Models/Post.cs, azure-pipelines.yml
Merging PostTesting branch to Modeltesting branch.
=> Merging PostTesting branch to Modeltesting branch.

Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/CommentsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/FollowsController.cs
=> Dto validation ttdpass

Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/CommentsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/FollowsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Controllers/PostsController.cs, Fakebook.Posts/Fakebook.Posts.RestApi/Services/BlobService.cs
A lot of methods were missing documentation, and often the documentation format between methods was different.  Helps finding the information you need easier.
=> Consistent documentation for controller methods added back
